"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import type { KeyboardEvent } from "react";
import type { Schema } from "@/amplify/data/resource";
type Section=Schema["Section"]["type"]; type Document=Schema["Document"]["type"];
function norm(v:unknown){return String(v??"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").trim()}
function score(q:string,v:string){const a=norm(q),b=norm(v);if(!a)return 0;if(b===a)return 1000;if(b.startsWith(a))return 900;if(b.includes(a))return 750;let at=0,hit=0;for(const c of a){const i=b.indexOf(c,at);if(i>=0){hit++;at=i+1}}return hit?hit/a.length*450:0}
export default function SearchPanel({sections,docs,onClose,onSelectSection,onSelectDocument,defaultSort}:{sections:Section[];docs:Document[];onClose:()=>void;onSelectSection:(s:Section)=>void;onSelectDocument:(d:Document)=>void;defaultSort:"relevance"|"newest"|"az"}){
 const inputRef=useRef<HTMLInputElement>(null);const[q,setQ]=useState("");const[scope,setScope]=useState<"all"|"section"|"pdf">("all");const[sectionId,setSectionId]=useState("all");const[sort,setSort]=useState<"relevance"|"newest"|"az">(defaultSort);const[active,setActive]=useState(0);
 useEffect(()=>{inputRef.current?.focus();const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=old}},[]);
 const results=useMemo(()=>{const query=norm(q);const s=sections.filter(x=>scope!=="pdf"&&(sectionId==="all"||x.id===sectionId)).map(x=>({kind:"section" as const,item:x,score:query?score(query,[x.name,x.description].join(" ")):0}));const d=docs.filter(x=>scope!=="section"&&(sectionId==="all"||x.sectionId===sectionId)).map(x=>({kind:"document" as const,item:x,score:query?score(query,[x.originalName,x.title,x.author].filter(Boolean).join(" ")):0})).filter(x=>!query||x.score>90);const all=[...s.filter(x=>!query||x.score>90),...d];if(sort==="az")all.sort((a,b)=>(a.kind==="section"?a.item.name:a.item.originalName||"").localeCompare(b.kind==="section"?b.item.name:b.item.originalName||""));else if(sort==="newest")all.sort((a,b)=>new Date(b.item.updatedAt||b.item.createdAt||0).getTime()-new Date(a.item.updatedAt||a.item.createdAt||0).getTime());else if(query)all.sort((a,b)=>b.score-a.score);return all.slice(0,18)},[docs,q,scope,sectionId,sections,sort]);
 useEffect(()=>setSort(defaultSort),[defaultSort]);
 useEffect(()=>setActive(0),[q,scope,sectionId,sort]);
 function choose(i:number){const r=results[i];if(!r)return;r.kind==="section"?onSelectSection(r.item):onSelectDocument(r.item);onClose()}
 function key(e:KeyboardEvent<HTMLInputElement>){if(e.key==="ArrowDown"){e.preventDefault();setActive(v=>Math.min(v+1,Math.max(0,results.length-1)))}if(e.key==="ArrowUp"){e.preventDefault();setActive(v=>Math.max(0,v-1))}if(e.key==="Enter"){e.preventDefault();choose(active)}if(e.key==="Escape"){e.preventDefault();onClose()}}
 return <div className="pd-search-panel-shell" role="dialog" aria-modal="true" aria-label="Library search" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div className="pd-search-panel">
  <header className="pd-search-panel-head"><div><span className="pd-kicker">PAPERDROP SEARCH</span><h2>Find anything in your library.</h2><p>Search PDFs and sections without leaving the page.</p></div><button type="button" className="pd-search-panel-close" onClick={onClose} aria-label="Close search">×</button></header>
  <div className="pd-search-panel-input"><span>⌕</span><input ref={inputRef} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={key} placeholder="Search PDFs, subjects, authors..." aria-label="Search PDFs, subjects and authors"/><kbd>ESC</kbd></div>
  <div className="pd-search-panel-tools"><div className="pd-search-scope">{([["all","Everything"],["pdf","PDFs"],["section","Sections"]] as const).map(([id,label])=><button key={id} type="button" className={scope===id?"is-active":""} onClick={()=>setScope(id)}>{label}</button>)}</div><div className="pd-search-selects"><select value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="all">All sections</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="relevance">Best match</option><option value="newest">Newest</option><option value="az">A–Z</option></select></div></div>
  <div className="pd-search-panel-body">{!q&&<div className="pd-search-banner"><div className="pd-search-banner-orb">✦</div><div><strong>Search like a command palette.</strong><p>Type a filename, author, subject or section. Use ↑ ↓ and Enter for keyboard-fast navigation.</p></div><span className="pd-search-shortcut">Ctrl / ⌘ K</span></div>}<div className="pd-search-panel-meta">{q ? "Results for “" + q + "”" : "Suggested destinations"}<span>{results.length} shown</span></div>{results.length?<div className="pd-search-panel-results">{results.map((r,i)=><button key={r.kind+r.item.id} type="button" className={"pd-search-panel-result "+(i===active?"is-active":"")} onMouseEnter={()=>setActive(i)} onClick={()=>choose(i)}><span className={"pd-search-result-icon "+r.kind}>{r.kind==="section"?"▦":"PDF"}</span><span className="pd-search-result-main"><strong>{r.kind==="section"?r.item.name:r.item.originalName}</strong><small>{r.kind==="section"?r.item.description||"Section":"PDF · "+(sections.find(s=>s.id===r.item.sectionId)?.name||"Library")}</small></span><span className="pd-search-result-arrow">↵</span></button>)}</div>:<div className="pd-search-empty"><strong>No matching results</strong><span>Try a filename, subject, author or section name.</span></div>}</div>
  <footer className="pd-search-panel-foot"><span>⌕ Global library search</span><span><kbd>↑↓</kbd> navigate <kbd>Enter</kbd> open <kbd>Esc</kbd> close</span></footer>
 </div></div>
}