"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { generateClient } from "aws-amplify/data";
import { uploadData } from "aws-amplify/storage";
import type { Schema } from "@/amplify/data/resource";
import { clearDraftUploads, formatSize, inspectPdf, isPdf, loadDraftUploads, saveDraftUploads, sha256, type DraftUpload } from "@/lib/paperdropl";
const client = generateClient<Schema>();
type Section = Schema["Section"]["type"];
type QueueItem = DraftUpload & { progress:number; status:"queued"|"uploading"|"done"|"error"|"duplicate"; error?:string };
type Props = { mode:"public"|"admin"; sections:Section[]; initialSectionId?:string; onClose?:()=>void; onSuccess?:(message:string)=>void; onRefresh?:()=>Promise<void>|void; compact?:boolean };
const MAX_SIZE=50*1024*1024;
function makeItem(file:File, sectionId:string):QueueItem{return{id:crypto.randomUUID(),name:file.name,size:file.size,type:file.type,file,sectionId,progress:0,status:"queued"}}
export default function UploadQueue({mode,sections,initialSectionId="",onClose,onSuccess,onRefresh,compact=false}:Props){
  const [items,setItems]=useState<QueueItem[]>([]); const [busy,setBusy]=useState(false); const [dragging,setDragging]=useState(false); const [message,setMessage]=useState(""); const [restorePrompt,setRestorePrompt]=useState(false); const inputRef=useRef<HTMLInputElement>(null);
  const firstSection=initialSectionId||sections[0]?.id||"";
  useEffect(()=>{loadDraftUploads().then(d=>{if(d.length)setRestorePrompt(true)})},[]);
  useEffect(()=>{const draft=items.filter(i=>i.status!=="done").map(({progress:_p,status:_s,error:_e,...item})=>item); void saveDraftUploads(draft)},[items]);
  const addFiles=useCallback((files:FileList|File[])=>{const accepted:QueueItem[]=[];const errors:string[]=[];for(const file of Array.from(files)){if(!isPdf(file)){errors.push(file.name+": PDF files only");continue}if(file.size>MAX_SIZE){errors.push(file.name+": maximum size is 50 MB");continue}accepted.push(makeItem(file,firstSection))}if(accepted.length)setItems(c=>[...c,...accepted]);if(errors.length)setMessage(errors.slice(0,3).join(" · "))},[firstSection]);
  async function restoreDraft(){setItems((await loadDraftUploads()).map(i=>({...i,progress:0,status:"queued" as const})));setRestorePrompt(false)}
  async function discardDraft(){await clearDraftUploads();setRestorePrompt(false)}
  const patch=(id:string,p:Partial<QueueItem>)=>setItems(c=>c.map(i=>i.id===id?{...i,...p}:i));
  async function processItem(item:QueueItem){if(!isPdf(item.file)||item.file.size>MAX_SIZE||!item.sectionId){patch(item.id,{status:"error",error:"Choose a section and a valid PDF under 50 MB."});return false}patch(item.id,{status:"uploading",progress:0,error:undefined});let path="";try{const hash=await sha256(item.file);const inspection=await inspectPdf(item.file);const authMode=mode==="admin"?"userPool":"identityPool";const [docs,subs]=await Promise.all([client.models.Document.list({authMode}),client.models.Submission.list({authMode})]);if(docs.errors?.length||subs.errors?.length)throw new Error(docs.errors?.[0]?.message||subs.errors?.[0]?.message||"Could not check duplicates.");const duplicateDoc=docs.data.find(d=>d.fileHash===hash);const duplicateSub=subs.data.find(s=>s.fileHash===hash&&s.status!=="rejected");if(duplicateDoc||duplicateSub){patch(item.id,{status:"duplicate",error:duplicateDoc?"Already published as \""+duplicateDoc.originalName+"\".":"Already submitted as \""+duplicateSub?.originalName+"\"."});return false}const objectId=crypto.randomUUID();path=(mode==="admin"?"public":"pending")+"/"+objectId+".pdf";await uploadData({path,data:item.file,options:{contentType:"application/pdf",onProgress:({transferredBytes,totalBytes})=>patch(item.id,{progress:Math.min(99,totalBytes?Math.round(transferredBytes/totalBytes*100):0)})}}).result;if(mode==="admin"){const r=await client.models.Document.create({originalName:item.name.slice(0,180),storagePath:path,size:item.size,sectionId:item.sectionId,status:"published",pageCount:inspection.pageCount,title:inspection.title,author:inspection.author,fileHash:hash,processingStatus:"complete",publishedAt:new Date().toISOString()},{authMode:"userPool"});if(r.errors?.length)throw new Error(r.errors[0].message)}else{const r=await client.models.Submission.create({originalName:item.name.slice(0,180),storagePath:path,size:item.size,sectionId:item.sectionId,status:"pending",pageCount:inspection.pageCount,title:inspection.title,author:inspection.author,fileHash:hash,processingStatus:"complete"},{authMode:"identityPool"});if(r.errors?.length)throw new Error(r.errors[0].message)}patch(item.id,{status:"done",progress:100});return true}catch(e){if(path&&mode==="admin"){const{remove}=await import("aws-amplify/storage");await remove({path}).catch(()=>undefined)}patch(item.id,{status:"error",progress:0,error:e instanceof Error?e.message:"Upload failed."});return false}}
  async function uploadAll(){if(busy)return;const work=items.filter(i=>i.status==="queued"||i.status==="error");if(!work.length)return;setBusy(true);setMessage("");let success=0;for(const item of work)if(await processItem(item))success++;setBusy(false);if(success){const msg=mode==="admin"?success+" PDF"+(success>1?"s":"")+" published successfully.":success+" PDF"+(success>1?"s":"")+" submitted for review.";setMessage(msg);onSuccess?.(msg);await clearDraftUploads();await onRefresh?.()}}
  const pending=items.filter(i=>i.status!=="done").length, done=items.filter(i=>i.status==="done").length;
  return <div className={"pd-uploader "+(compact?"pd-uploader-compact":"")}><div className="pd-uploader-head"><div><span className="pd-kicker">{mode==="admin"?"ADMIN PUBLISH":"SHARE KNOWLEDGE"}</span><h2>{mode==="admin"?"Publish PDFs":"Drop your PDFs"}</h2><p>{mode==="admin"?"Publish directly to the public library.":"Files stay private until an admin approves them."}</p></div>{onClose&&<button type="button" className="pd-icon-button" onClick={onClose}>×</button>}</div>
  <div className={"pd-dropzone "+(dragging?"is-dragging":"")} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={e=>{e.preventDefault();if(e.currentTarget===e.target)setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);addFiles(e.dataTransfer.files)}} onClick={()=>inputRef.current?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")inputRef.current?.click()}}><input ref={inputRef} className="pd-hidden-file-input" type="file" accept="application/pdf,.pdf" multiple onChange={e=>{if(e.target.files)addFiles(e.target.files);e.currentTarget.value=""}}/><div className="pd-drop-icon">＋</div><strong>Drop PDF files here</strong><span>or tap to choose • up to 50 MB each</span></div>
  {message&&<div className="pd-upload-message">{message}</div>}{restorePrompt&&<div className="pd-draft"><strong>Unfinished upload draft found.</strong><span>It was saved on this device.</span><div className="pd-draft-actions"><button type="button" className="pd-primary-sm" onClick={restoreDraft}>Restore</button><button type="button" className="pd-secondary-sm" onClick={discardDraft}>Discard</button></div></div>}
  {items.length>0&&<div className="pd-queue">{items.map(item=><div className="pd-queue-item" key={item.id}><div className="pd-queue-main"><div className="pd-pdf-badge">PDF</div><div className="pd-queue-copy"><strong title={item.name}>{item.name}</strong><span>{formatSize(item.size)} · {item.status==="uploading"?item.progress+"%":item.status}</span></div></div><select value={item.sectionId} disabled={busy||item.status==="done"} onChange={e=>patch(item.id,{sectionId:e.target.value})}><option value="">Choose section</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{item.status==="uploading"&&<div className="pd-progress"><span style={{width:item.progress+"%"}}/></div>}{item.error&&<small className="pd-queue-error">{item.error}</small>}<div className="pd-queue-actions">{(item.status==="error"||item.status==="duplicate")&&<button type="button" onClick={()=>patch(item.id,{status:"queued",error:undefined})}>Retry</button>}{item.status!=="done"&&<button type="button" disabled={busy} onClick={()=>{if(!busy)setItems(c=>c.filter(i=>i.id!==item.id))}}>Remove</button>}{item.status==="done"&&<span className="pd-done">✓ Done</span>}</div></div>)}</div>}
  <div className="pd-uploader-footer"><span>{done} complete · {pending} remaining</span><div className="pd-uploader-actions"><button type="button" className="pd-secondary-sm" disabled={busy||!items.length} onClick={()=>setItems([])}>Clear</button><button type="button" className="pd-primary-sm" disabled={busy||!items.some(i=>i.status==="queued"||i.status==="error")} onClick={uploadAll}>{busy?"Uploading…":mode==="admin"?"Publish all":"Submit all"}</button></div></div></div>;